phpbb_cannedmessages_selected:
    path: /cannedmessageselected/{data}
    defaults: { _controller: phpbb.cannedmessages.selected.controller:handle, mode: retrieve }
    requirements:
        data: \d+
